# Generated by Django 4.2.5 on 2023-09-18 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ride_finder", "0007_car_user_car_alter_ride_user_car"),
        ("users", "0002_car_profile_phone_number_user_car"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_car",
            name="car",
        ),
        migrations.RemoveField(
            model_name="user_car",
            name="user",
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="User_Car",
        ),
    ]
