# Generated by Django 4.2.5 on 2023-09-18 00:18

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("ride_finder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="destination",
            field=address.models.AddressField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.address",
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="start",
            field=address.models.AddressField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="start_address",
                to="address.address",
            ),
        ),
    ]
