# Generated by Django 4.2.5 on 2023-09-18 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ride_finder", "0003_request_status_ride_seats_request"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request_Status",
            new_name="RequestStatus",
        ),
    ]
