# Generated by Django 4.2.5 on 2023-09-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ride_finder", "0004_rename_request_status_requeststatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requeststatus",
            name="description",
        ),
        migrations.AddField(
            model_name="request",
            name="description",
            field=models.CharField(default="descr", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="request_status",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="ride_finder.requeststatus",
            ),
        ),
    ]
