# Generated by Django 4.2.5 on 2023-09-18 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride_finder", "0006_ride_user_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name="User_Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ride_finder.car",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ride",
            name="user_car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ride_finder.user_car"
            ),
        ),
    ]
