# Generated by Django 4.2.5 on 2023-12-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ride_finder", "0008_remove_ride_user_car_car_user_delete_user_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="car",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ride_finder.car",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
