# Generated by Django 4.2.5 on 2023-12-20 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ride_finder", "0009_ride_car_alter_car_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="seats",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
